# Generated by Django 5.2.8 on 2025-12-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualPaymentRequest',
        ),
    ]
